### PR TITLE
Notify P2P in case of bad preconfirmation message

### LINKED ISSUE #2872: Handle invalid pre confirmations from the gossipsub protocol
Decrease reputation of the peer if it sends incorrect preconfirmations or delegate keys.
`TxStatusManager` should report to the P2P about validity of the messages.

### PR DESCRIPTION
**Pull request by AurelienFT**
## Linked Issues/PRs
Resolves #2872

## Description
In this PR the `TxStatusManager` can report to P2P bad messages

## Checklist
- [x] Breaking changes are clearly marked as such in the PR description and changelog
- [x] New behavior is reflected in tests
- [x] [The specification](https://github.com/FuelLabs/fuel-specs/) matches the implemented behavior (link update PR if changes are needed)

### Before requesting review
- [x] I have reviewed the code myself
- [x] I have created follow-up issues caused by this PR and linked them here

### CODE REVIEW

File: crates/services/tx_status_manager/src/service.rs [hunk 1]
```diff
@@ -224,7 +230,19 @@ impl<Pubkey: ProtocolPublicKey> Task<Pubkey> {
                 );
                 // TODO: Report peer for sending invalid delegation
                 //  https://github.com/FuelLabs/fuel-core/issues/2872
-                let _ = self.signature_verification.add_new_delegate(&sealed);
+                if !self.signature_verification.add_new_delegate(&sealed) {
```
[the remark this answers is not in the document]
Comment (AurelienFT) [reply crates/services/tx_status_manager/src/service.rs:231]: Done.

File: crates/services/tx_status_manager/src/service.rs [hunk 2]
```diff
@@ -260,21 +284,43 @@ impl<Pubkey: ProtocolPublicKey> Task<Pubkey> {
...
                 }
             }
         }
     }
 }
 
 #[async_trait::async_trait]
-impl<Pubkey: ProtocolPublicKey> RunnableService for Task<Pubkey> {
+impl<Pubkey: ProtocolPublicKey, P2P: P2PSubscriptions> RunnableService
+    for Task<Pubkey, P2P>
```
Comment (rymnc) [inline crates/services/tx_status_manager/src/service.rs:322]:
```suggestion
impl<Pubkey, P2P> RunnableService
    for Task<Pubkey, P2P>
where
    Pubkey: ProtocolPublicKey,
    P2P: P2PSubscriptions
```

File: crates/services/tx_status_manager/src/service.rs [hunk 3]
```diff
@@ -293,7 +339,9 @@ impl<Pubkey: ProtocolPublicKey> RunnableService for Task<Pubkey> {
     }
 }
 
-impl<Pubkey: ProtocolPublicKey> RunnableTask for Task<Pubkey> {
+impl<Pubkey: ProtocolPublicKey, P2P: P2PSubscriptions> RunnableTask
+    for Task<Pubkey, P2P>
```
Comment (rymnc) [inline crates/services/tx_status_manager/src/service.rs:343]:
```suggestion
impl<Pubkey, P2P> RunnableTask
    for Task<Pubkey, P2P>
where
    Pubkey: ProtocolPublicKey,
    P2P: P2PSubscriptions
```

File: crates/services/tx_status_manager/src/service.rs [hunk 4]
```diff
@@ -501,12 +553,40 @@ mod tests {
...
+        }
+
+        fn notify_gossip_transaction_validity(
+            &self,
+            _message_info: GossipsubMessageInfo,
+            _validity: GossipsubMessageAcceptance,
+        ) -> anyhow::Result<()> {
+            self.p2p_notify_validity_sender
+                .try_send((_message_info, _validity))
+                .unwrap();
```
Comment (rymnc) [inline crates/services/tx_status_manager/src/service.rs:577]:
```suggestion
            message_info: GossipsubMessageInfo,
            validity: GossipsubMessageAcceptance,
        ) -> anyhow::Result<()> {
            self.p2p_notify_validity_sender
                .try_send((message_info, validity))
                .unwrap();
```

**Review by rymnc — COMMENTED** [review]
can we have an integ test for this? 
to ensure that an invalid delegate key is being rejected and not forwarded by a particular node via gossipsub?

**Comment by AurelienFT** [comment]
@rymnc the test was here for preconfirmation message but not delegate key message I added one.

**Review by rymnc — APPROVED** [review]

**Review by xgreenx — APPROVED** [review]
