### PR TITLE
fix(api_service): exclude health checks from throttling with ConcurrencyLimitLayer

### LINKED ISSUE #2319: `/health` endpoint maybe be queued causing false positive restart for operators
The `/health` endpoint now is also limited by concurrency limit after https://github.com/FuelLabs/fuel-core/pull/2309

image

If the node has a lot of queries it can be terminated by failing liveness check for node operators.

### PR DESCRIPTION
**Pull request by rymnc**
## Linked Issues/PRs

closes #2319

## Description

Uses axum's `merge` chaining operator to add the `ConcurrencyLimit Layer` only on subsets of the routes we serve, and exclude `/health` from it.

We retain `/metrics` to be throttled, because it acquires a lock on the `GLOBAL_REGISTER`, which may prevent Prometheus from reading metrics. This is a double-edged sword though i think.

## Checklist
- [x] Breaking changes are clearly marked as such in the PR description and changelog
- [x] New behavior is reflected in tests
- [x] [The specification](https://github.com/FuelLabs/fuel-specs/) matches the implemented behavior (link update PR if changes are needed)

### Before requesting review
- [x] I have reviewed the code myself
- [ ] I have created follow-up issues caused by this PR and linked them here

### After merging, notify other teams

[Add or remove entries as needed]

- [ ] [Rust SDK](https://github.com/FuelLabs/fuels-rs/)
- [ ] [Sway compiler](https://github.com/FuelLabs/sway/)
- [ ] [Platform documentation](https://github.com/FuelLabs/devrel-requests/issues/new?assignees=&labels=new+request&projects=&template=NEW-REQUEST.yml&title=%5BRequest%5D%3A+) (for out-of-organization contributors, the person merging the PR will do this)
- [ ] Someone else?

### CODE REVIEW

File: crates/fuel-core/src/graphql_api/api_service.rs [hunk 1]
```diff
@@ -221,17 +221,26 @@ where
...
-    let router = Router::new()
-        .route("/v1/playground", get(graphql_playground))
-        .route("/v1/graphql", post(graphql_handler).options(ok))
-        .route(
-            "/v1/graphql-sub",
-            post(graphql_subscription_handler).options(ok),
-        )
-        .route("/v1/metrics", get(metrics))
+    let unthrottled_routes = Router::new()
+        // we shouldn't throttle these requests
```
Comment (netrome) [inline crates/fuel-core/src/graphql_api/api_service.rs:225]: Nit: I think the variable name is clear enough here.
```suggestion
```

File: crates/fuel-core/src/graphql_api/api_service.rs [hunk 2]
```diff
@@ -221,17 +221,26 @@ where
...
         .route("/v1/health", get(health))
-        .route("/health", get(health))
-        .layer(ConcurrencyLimitLayer::new(concurrency_limit))
+        .route("/health", get(health));
+
+    let throttled_routes =
+        // we should throttle these requests
```
Comment (netrome) [inline crates/fuel-core/src/graphql_api/api_service.rs:230]:
```suggestion
```

**Review by netrome — DISMISSED** [review]
Nice stuff! Just a nit suggestion, but feel free to skip it.

File: crates/fuel-core/src/graphql_api/api_service.rs (hunk 1 above)
Comment (rymnc) [reply crates/fuel-core/src/graphql_api/api_service.rs]: addressed in aa651b81a6

File: crates/fuel-core/src/graphql_api/api_service.rs (hunk 2 above)
Comment (rymnc) [reply crates/fuel-core/src/graphql_api/api_service.rs]: addressed in aa651b81a6

**Review by netrome — APPROVED** [review]

**Review by netrome — APPROVED** [review]

File: CHANGELOG.md [hunk 3]
```diff
@@ -6,6 +6,9 @@ and this project adheres to [Semantic Versioning](http://semver.org/).
 
 ## [Unreleased]
 
+## Fixed
+- [2320](https://github.com/FuelLabs/fuel-core/issues/2320): Prevent `/health` from being throttled by the concurrency limiter.
```
Comment (rafal-ch) [inline CHANGELOG.md:10]: Should this be like below?

```suggestion
- [2320](https://github.com/FuelLabs/fuel-core/issues/2320): Prevent `/health` and `/v1/health` from being throttled by the concurrency limiter.
```

**Review by rafal-ch — COMMENTED** [review]
Looks good, I just have one minor question.

**Review by rafal-ch — APPROVED** [review]

**Review by netrome — DISMISSED** [review]

File: crates/fuel-core/src/graphql_api/api_service.rs [hunk 4]
```diff
@@ -221,17 +221,23 @@ where
...
         .route("/v1/graphql", post(graphql_handler).options(ok))
         .route(
             "/v1/graphql-sub",
             post(graphql_subscription_handler).options(ok),
         )
         .route("/v1/metrics", get(metrics))
-        .route("/v1/health", get(health))
-        .route("/health", get(health))
-        .layer(ConcurrencyLimitLayer::new(concurrency_limit))
+        .layer(ConcurrencyLimitLayer::new(concurrency_limit));
```
Comment (xgreenx) [inline crates/fuel-core/src/graphql_api/api_service.rs:236]: I think we want something like. Because graph-sub also is limited by number of subscriptions, and playground is one time query that returns pre rendered html

image

Comment (rymnc) [reply crates/fuel-core/src/graphql_api/api_service.rs:236]: > Throteling metrics doesn't allow request data=)
are you saying that because metrics are throttled, it affects how graphql and graphql-sub are throttled as well? 

why shouldn't we throttle the metrics?

Comment (xgreenx) [reply crates/fuel-core/src/graphql_api/api_service.rs:236]: Because if we have a lot of queries, it becomes impossible for us to track the state of the node from the Grafana=)

Comment (rymnc) [reply crates/fuel-core/src/graphql_api/api_service.rs:236]: okay, making the change

Comment (rymnc) [reply crates/fuel-core/src/graphql_api/api_service.rs]: addressed in 1a66422487

**Review by netrome — APPROVED** [review]

**Review by xgreenx — APPROVED** [review]
