### PR TITLE
Rollback unsuccessful preconfs in the mempool

### LINKED ISSUE #3098: Rollback unsuccessful preconfs in the mempool
When the mempool receives a pre-confirmation, it optimistically marks the inputs as "spent" in it's local cache. 

Currently there is no mechanism to rollback failed preconfs in the mempool, apart from a full restart of the node. This means when a preconfirmation doesn't finalize, those inputs remain "stuck", and users are prevented from using those inputs until the mempool is reset.

This has been observed nearly anytime the block producer is restarted, we find there are stuck utxos in the RPC mempools.

1. We need to investigate why restarting the block producer causes so many dropped transactions from a pre-conf perspective. Ideally if there is graceful shutdown, the in-flight blocks / transactions get finalized before the process exits.
2. We need a mechanism to automatically clear these cached utxos in the mempool without manual intervention (i.e. rebooting the mempool), either via TTL or some other reconciliation process that detects if a transaction did not finalize. Ie. any cached preconf data older than 1 block ago should be discarded.

### PR DESCRIPTION
**Pull request by Dentosal**
Closes #3098.

## Problem

When a block producer sends preconfirmation updates, sentry nodes optimistically treat the included transactions as committed, removing them from the mempool and marking their inputs as spent. If the producer crashes and re-produces a block at the same height without those transactions, the mempool is left in a stale state: inputs stay marked as spent and outputs linger in `extracted_outputs`, preventing re-submission of rolled-back transactions and causing dependents to reference non-existent UTXOs.

## Solution

This PR makes preconfirmed transactions tentative until the canonical block at their height is imported. On import, preconfirmed txs present in the block are confirmed and their tracking is cleared; those absent are rolled back by restoring inputs, purging dependents, and emitting `SqueezedOut` notifications. It also adds integration tests: re-insertion after rollback, dependent eviction, normal confirmation, and stale-height cleanup.

## Checklist
- [x] Breaking changes are clearly marked as such in the PR description and changelog
- [x] New behavior is reflected in tests
- [x] [The specification](https://github.com/FuelLabs/fuel-specs/) matches the implemented behavior (link update PR if changes are needed)

### Before requesting review
- [ ] I have reviewed the code myself
- [x] I have created follow-up issues caused by this PR and linked them here

### CODE REVIEW

File: crates/services/txpool_v2/src/spent_inputs.rs [hunk 1]
```diff
@@ -27,13 +27,17 @@ pub struct SpentInputs {
     /// transaction spent it. Later, this information can be used to unspent
     /// or fully spend the input.
     spender_of_inputs: HashMap<TxId, Vec<InputKey>>,
+    /// Inputs permanently spent during preconfirmation processing, saved so
+    /// they can be rolled back if the preconfirmation turns out to be stale.
+    tentative_spent: HashMap<TxId, Vec<InputKey>>,
```
Comment (MitchTurner) [inline crates/services/txpool_v2/src/spent_inputs.rs:32]: Is there any chance that his will grow indefinitely?

Seems fine to me. It's not good to test internal values anyway, but worth considering if this is a "leak" in any way.

**Review by MitchTurner — COMMENTED** [review]
The logic looks good to me. 

I've noticed that our code has a lot more comments than it has in the past. I assume this is due to agents we are using. I'm of the opinion that we include an `AGENTS.md` file in our repos to ensure that we follow some standards. I don't mind the comments in the domain code--although I don't like a ton--I definitely don't like so many in the tests though. 

nit: the test are using given/when/then kinda, but aren't following the `send__when_x_then_y_happens` pattern which in conjunction with removing the comments would make them easier to read.

**Comment by Dentosal** [comment]
> I've noticed that our code has a lot more comments than it has in the past. I assume this is due to agents we are using. I'm of the opinion that we include an `AGENTS.md` file in our repos to ensure that we follow some standards.

Sounds reasonable.

> I don't mind the comments in the domain code--although I don't like a ton--I definitely don't like so many in the tests though.

I personally like having more comments rather than less. IMO our codebases are very under-commented when it comes to reasons why things look like they do, and this makes it rather it hard to follow i.e. what a field is used for. This is especially nice in tests which are most of the time written once and rarely touched again.

> nit: the test are using given/when/then kinda, but aren't following the `send__when_x_then_y_happens` pattern which in conjunction with removing the comments would make them easier to read.

I much prefer the style where the human readable text is in a comment block and the test name is mostly used as a shorthand identifier.

File: crates/services/txpool_v2/src/spent_inputs.rs (hunk 1 above)
Comment (Dentosal) [reply crates/services/txpool_v2/src/spent_inputs.rs:32]: I don't think so, unless blocks are not getting imported at all. These are always cleared for when the associated block height gets imported.

**Comment by MitchTurner** [comment]
> I much prefer the style where the human readable text is in a comment block and the test name is mostly used as a shorthand identifier.

In it's best form, the `send__` style of tests end up being a series of small tests that you can quickly check the behavior/coverage. So if your tests all start looking like each other, and are only 10-20 lines long, you can quickly understand the scope of all your tests. i.e. If I'm checking coverage of my code, having 10 short tests is much less cognitive overhead, where the differences are encapsulated in the name of one variable and the  `expect` in the `//then` block, rather than having to read each test anew.

That's the vision.

**Comment by Voxelot** [comment]
I think there is still a rollback gap for spent-input cleanup in the producer-local extracted-first path.

The happy paths seem fine:

1. Sentry / non-extracted path
- T is still in txpool when the preconfirmation arrives
- `process_preconfirmed_committed_transaction(T)` finds T in `tx_id_to_storage_id`
- it records rollback state with `record_tentative_spend(T, inputs)`
- if canon later omits T, `unspend_preconfirmed(T)` restores those inputs from `tentative_spent`

2. Local producer / extracted path where T becomes canonical
- T is extracted first, so `maybe_spend_inputs(T, inputs)` marks T’s inputs as spent in `spent_inputs` and stores the input list in `spender_of_inputs[T]`
- later the local preconfirmation arrives and `spend_inputs_by_tx_id(T)` drains `spender_of_inputs[T]`
- if the canonical block includes T, this is fine: the inputs are supposed to remain spent, and no rollback is needed

The unhappy path is local producer + rollback:

1. T is extracted for production
2. `maybe_spend_inputs(T, inputs)` does two things:
   - marks T’s inputs as spent in `spent_inputs`
   - stores the same input list in `spender_of_inputs[T]`
3. T is removed from pool storage/selection
4. local preconfirmation for T arrives
5. `process_preconfirmed_committed_transaction(T)` calls `spend_inputs_by_tx_id(T)`
6. `spend_inputs_by_tx_id(T)` drains `spender_of_inputs[T]`, but it does NOT clear those inputs from `spent_inputs`:
   - it removes the bookkeeping entry
   - it leaves/reapplies the live spent markers in `spent_inputs`
7. because T was already extracted, it is no longer in `tx_id_to_storage_id`, so the branch that calls `record_tentative_spend(T, inputs)` is skipped
8. later the canonical block omits T
9. `rollback_preconfirmed_transaction(T)` calls `unspend_preconfirmed(T)`
10. `unspend_preconfirmed(T)` only clears:
   - `InputKey::Tx(T)`
   - the per-input keys saved in `tentative_spent[T]`
11. but `tentative_spent[T]` was never populated in this extracted-first path
12. so T’s coin/message input keys remain present in `spent_inputs`

That is the bug: the original inputs remain marked spent in `spent_inputs`, but the metadata needed to clear them was lost when `spender_of_inputs[T]` was drained and never copied into `tentative_spent[T]`. **This means these inputs will be silently rejected by the authority node (ie p2p message rejection) until they expire from the LRU cache, blocking the user from retrying their transaction!**

Suggested fix direction:
- when a preconfirmation arrives for an already-extracted tx, preserve the original input keys in rollbackable state before `spend_inputs_by_tx_id(T)` drains `spender_of_inputs[T]`
- in other words, the extracted / `maybe_spent` state needs to transition into `tentative_spent`, even when the tx is no longer present in `tx_id_to_storage_id`

I think this needs a regression test covering:
- producer extracts T
- producer locally processes preconfirmation for T
- canonical block at that height omits T
- T’s original inputs are no longer present in `spent_inputs`

**Comment by Voxelot** [comment]
Another potential rollback gap to consider is transactions that were admitted only because a preconfirmed tx temporarily created a contract.

The coin-dependent rollback path looks covered, but I do not see equivalent cleanup for contract-created dependents. The happy path is straightforward: if a preconfirmed tx `P` creates contract `C`, and a dependent tx `D` using `Input::Contract(C, ...)` is admitted while that preconfirmation is live, then everything is fine if the canonical block later includes `P`, because `C` really exists.

The concerning case is when `P` is preconfirmed, txpool records that temporary contract existence in `extracted_outputs`, and `D` is admitted because validation accepts `extracted_outputs.contract_exists(...)`, but the canonical block at that height later omits `P`. Rollback clears the extracted outputs for `P`, but `rollback_preconfirmed_transaction(P)` appears to remove dependents only through `get_coins_spenders(P)`. I do not see a symmetric cleanup path for txs that were admitted only because the temporary contract existed.

So this looks like a separate rollback edge case: the temporary contract creation can be removed, but a dependent tx that was only valid because of that temporary contract may still remain in the pool.

It would probably be worth either adding symmetric contract-dependent tracking alongside `get_coins_spenders(...)`, or deriving those dependents from the dependency graph during rollback. I think this also needs a regression test covering a preconfirmed tx that creates a contract, a dependent tx inserted via `Input::Contract(...)`, and then rollback when the canonical block omits the creator.

**Comment by Voxelot** [comment]
A third thing worth considering is stale preconfirmations that arrive after the node has already imported a newer canonical block.

This feels less like a pure cleanup/rollback issue and more like an admission check: I do not see `process_preconfirmed_transaction(...)` rejecting a preconfirmation whose `tx_pointer.block_height()` is already at or below the node’s current canonical height.

That means if the node has already imported canonical height `H`, and a delayed preconfirmation later arrives for some height `<= H`, txpool can still apply it immediately:
- mark the tx as committed from txpool’s perspective
- insert its `resolved_outputs` into `extracted_outputs`
- admit dependents against those outputs
- mark inputs spent

This is only really a problem if the late preconfirmation is for a tx that did not actually end up in the canonical block at the height referenced by its `tx_pointer`. In that case, the preconfirmation is now stale, but txpool will still temporarily treat it as live. That can block the tx’s original inputs from being usable, and can also temporarily admit dependents against outputs that never became canonical.

This PR will eventually reconcile that state on a later block import, so it is not necessarily permanent corruption. But it does create a real stale-acceptance window where txpool can temporarily treat old, non-canonical preconfirmed state as live until the next block import arrives.

So I think there is a real correctness risk here, not just a defensive tidy-up. If stale preconfirmations can arrive late, they should probably be ignored before mutating txpool state whenever `preconf_height <= current_canonical_height`.

I think this needs a regression test covering:
- node imports canonical block at height `H`
- delayed preconfirmation later arrives for height `<= H`
- the referenced tx is not in the canonical block at that height
- txpool ignores the preconfirmation and does not mutate `spent_inputs` / `extracted_outputs`

File: crates/services/txpool_v2/src/collision_manager/basic.rs [hunk 2]
```diff
@@ -67,6 +71,7 @@ impl<StorageIndex> BasicCollisionManager<StorageIndex> {
             messages_spenders: HashMap::new(),
             coins_spenders: BTreeMap::new(),
             contracts_creators: HashMap::new(),
+            contract_users: HashMap::new(),
```
[the remark this answers is not in the document]
Comment (Dentosal) [reply crates/services/txpool_v2/src/collision_manager/basic.rs:74]: Fixed in 84b0c4ab36

**Comment by Dentosal** [comment]
@Voxelot Addressed all these in 01410e0. I mostly followed your suggested fixes. I added tests for all of them too.

**Review by Voxelot — APPROVED** [review]
fixes look good, not sure why ci isn't happy though. will approve again if needed once xi is passing.

File: crates/services/txpool_v2/src/pool.rs [hunk 3]
```diff
@@ -685,6 +731,87 @@ where
...
+        // Capture contracts created by this preconfirmation BEFORE clearing
+        // extracted_outputs, so we can evict any pool txs that were admitted
+        // only because of the now-stale temporary contract existence.
+        let created_contracts: Vec<_> =
+            self.extracted_outputs.contracts_created_by(&tx_id).to_vec();
+
+        // Remove preconfirmed outputs so dependents can't use them.
+        self.extracted_outputs.new_skipped_transaction(&tx_id);
+        // Allow the transaction itself to be re-submitted.
+        self.spent_inputs.unspend_preconfirmed(tx_id);
```
[the remark this answers is not in the document]
Comment (Voxelot) [reply crates/services/txpool_v2/src/pool.rs:748]: @Dentosal I don't think this is a real issue in practice, as we only use utxo_validation = false as a developer/debug mode.

File: crates/services/txpool_v2/src/collision_manager/basic.rs [hunk 4]
```diff
@@ -298,7 +348,14 @@ where
...
                 }
-                _ => {}
+                Input::Contract(ContractInput { contract_id, .. }) => {
+                    if let Some(users) = self.contract_users.get_mut(contract_id) {
+                        users.retain(|id| id != &tx_id);
+                        if users.is_empty() {
+                            self.contract_users.remove(contract_id);
+                        }
+                    }
+                }
```
Comment (xgreenx) [inline crates/services/txpool_v2/src/collision_manager/basic.rs:358]: I think removing transaction IDs here, you will not have access to them during `rollback_preconfirmed_transaction`. Because we remove it when a transaction is included in the block during production, while you call `rollback_preconfirmed_transaction` after block is done, so you will not have access to them. It only should affect authority, I guess, so maybe it is fine. I think sentries should still be able to work with it. But maybe we want to move this clean up int o`process_block`

Comment (Dentosal) [reply crates/services/txpool_v2/src/collision_manager/basic.rs:358]: Follow-up: https://github.com/FuelLabs/fuel-core/pull/3268
