### PR TITLE
Ignore receipts from failed transactions in `message_receipts_proof`

### LINKED ISSUE #2421: `message_receipts_proof` creates invalid proof if transaction with `MessageOut` receipt failed
The `message_receipts_proof` function creates invalid proof if transaction with `MessageOut` receipt failed during execution of the block.

The code creates Merkle tree over all `MessageOut` receipts even if transaction failed. While the `message_outbox_root` includes only messages from successful transactions.

image
image

## Definition of done

The user should be able to generate valid proof for blocks containing successful and failed transactions that emit a `MessageOut` receipt.

### PR DESCRIPTION
**Pull request by AurelienFT**
Resolves #2421 

In this PR we changed the  `message_receipts_proof` to ignore the receipts from the failed transactions.

## Checklist
- [x] Breaking changes are clearly marked as such in the PR description and changelog
- [x] New behavior is reflected in tests
- [x] [The specification](https://github.com/FuelLabs/fuel-specs/) matches the implemented behavior (link update PR if changes are needed)

### Before requesting review
- [x] I have reviewed the code myself
- [x] I have created follow-up issues caused by this PR and linked them here

### CODE REVIEW

File: crates/fuel-core/src/query/message.rs [hunk 1]
```diff
@@ -278,7 +278,11 @@ fn message_receipts_proof<T: MessageProofData + ?Sized>(
     // Get the message receipts from the block.
     let leaves: Vec<Vec<Receipt>> = message_block_txs
         .iter()
-        .map(|id| database.receipts(id))
```
Comment (xgreenx) [inline crates/fuel-core/src/query/message.rs:281]: Maybe we also need to update another place with `database.receipts` function call. And remove `receipts` function at all=)

image

File: crates/fuel-core/src/query/message.rs [hunk 2]
```diff
@@ -337,3 +341,184 @@ pub fn message_status(
...
+    fn test_message_receipts_proof_ignore_failed() {
+        // Create a fake database
+        let mut database = FakeDB::new();
+
+        // Given
+        // Create a block with a valid transaction and receipts
+        let mut block = CompressedBlock::default();
+        let valid_tx_id = Bytes32::new([1; 32]);
+        let mut valid_tx_receipts = vec![];
+        for i in 0..100 {
```
Comment (xgreenx) [inline crates/fuel-core/src/query/message.rs:448]: Why do we need `100` receipts?=D

File: crates/fuel-core/src/query/message.rs [hunk 3]
```diff
@@ -337,3 +341,184 @@ pub fn message_status(
...
+                receipts: valid_tx_receipts.clone(),
+                total_fee: 0,
+                total_gas: 0,
+                result: None,
+            },
+        );
+        database.insert_receipts(valid_tx_id, valid_tx_receipts.clone());
+
+        // Get the message proof with the valid transaction
+        let message_proof_valid_tx = message_receipts_proof(
```
Comment (xgreenx) [inline crates/fuel-core/src/query/message.rs:475]: It would be nice if we tested public function `message_proof` instead of the private

File: crates/fuel-core/src/query/message.rs (hunk 2 above)
Comment (AurelienFT) [reply crates/fuel-core/src/query/message.rs:448]: Its in order to build a bigger tree and have some path for the proof. It could be 10 also.

File: crates/fuel-core/src/query/message.rs (hunk 3 above)
Comment (AurelienFT) [reply crates/fuel-core/src/query/message.rs]: Done

File: crates/fuel-core/src/query/message.rs [hunk 4]
```diff
@@ -337,3 +332,173 @@ pub fn message_status(
...
+
+        // When
+        // Get the message proof with the same message id
+        let message_proof_invalid_tx =
+            message_proof(&database, valid_tx_id, Nonce::default(), block_height)
+                .unwrap();
+
+        // Then
+        // The proof should be the same because the invalid transaction was ignored
+        assert_eq!(message_proof_valid_tx, message_proof_invalid_tx);
```
Comment (xgreenx) [inline crates/fuel-core/src/query/message.rs:502]: Have you tested it without the fix, and it was failing here, yeah?

**Review by xgreenx — APPROVED** [review]
Looks good to me=) I hope the answer on my question is "yes"=D

File: crates/fuel-core/src/query/message.rs (hunk 4 above)
Comment (AurelienFT) [reply crates/fuel-core/src/query/message.rs:502]: "yes" :)

**Review by netrome — APPROVED** [review]
Nice stuff!
