### PR TITLE
Add Metrics to Batch Write and Key Length Fix

### LINKED ISSUE #416: Enhance DB Metrics
[Explained here](https://github.com/FuelLabs/fuel-core/pull/404#discussion_r898317340)

Metric meters should be incremented when calling batch db operations, and include key_length when incrementing bytes for `iter_all`

### PR DESCRIPTION
**Pull request by ControlCplusControlV**
Closes #416 , added a script and a submit call to ensure `batch_write` is actually tested with metrics. Working fine and minimal changes, just a quick fix.

### CODE REVIEW

File: fuel-core/src/state/rocks_db.rs [hunk 1]
```diff
@@ -229,7 +230,13 @@ impl BatchOperations for RocksDb {
                 }
             }
         }
-
+        #[cfg(feature = "prometheus")]
+        {
+            DATABASE_METRICS.write_meter.inc();
+            DATABASE_METRICS
+                .bytes_written_meter
+                .inc_by(batch.len() as u64);
```
Comment (Voxelot) [inline fuel-core/src/state/rocks_db.rs:238]: Looking at the [docs](https://docs.rs/rocksdb/0.17.0/rocksdb/struct.WriteBatch.html#method.len), it seems like we should be using `size_in_bytes` instead:

```suggestion
                .inc_by(batch.size_in_bytes() as u64);
```

Comment (ControlCplusControlV) [reply fuel-core/src/state/rocks_db.rs:238]: good catch

**Review by Voxelot — APPROVED** [review]
